"""fix category unique constraint

Revision ID: 5eae301d7ed1
Revises: 9378e17e19c6
Create Date: 2025-12-30 08:03:23.087244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5eae301d7ed1"
down_revision: Union[str, Sequence[str], None] = "9378e17e19c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.drop_constraint(op.f("categories_name_key"), "categories", type_="unique")
    op.create_unique_constraint(
        "uq_user_category_name", "categories", ["user_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("uq_user_category_name", "categories", type_="unique")
    op.create_unique_constraint(
        op.f("categories_name_key"),
        "categories",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
