"""Add is_admin to users

Revision ID: e0373696d13f
Revises: 5eae301d7ed1
Create Date: 2025-12-30 11:58:12.046026

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0373696d13f"
down_revision: Union[str, Sequence[str], None] = "5eae301d7ed1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Добавляем колонку как nullable=True (разрешаем пустые значения на время)
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))

    # 2. Заполняем существующие строки значением по умолчанию (False)
    # Используем op.execute для выполнения прямого SQL
    op.execute("UPDATE users SET is_admin = False")

    # 3. Теперь, когда NULL-ов больше нет, делаем колонку NOT NULL
    op.alter_column("users", "is_admin", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
